modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Bram1903/MarlowsCrystalOptimizer/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "Optimization that fixes waiting on the server after crystal break before end crystal entities are cleaned."
authors = "Bram, Marlow"
logoFile = "assets/marlows-crystal-optimizer/icon.png"
iconFile = "assets/marlows-crystal-optimizer/icon.png"
iconBlur = true
displayURL = "https://modrinth.com/mod/marlow-crystal-optimizer"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "MarlowCrystal.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
